name: Publish Release

on:
  release:
    types: [published]

jobs:
  homebrew:
      name: Bump Homebrew formula
      runs-on: ubuntu-latest
      steps:
        - uses: mislav/bump-homebrew-formula-action@v1
          with:
            formula-name: flow-cli
          env:
            COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
